package org.delta.web.ucase.constants;

public interface BSConfigurationConstants {

	// Connection Configuration + EndPoint URL
	String BS_DELTA_CON_TYPE = "CONNECTION_TYPE";
	String	BS_DELTA_USERNAME = "USERNAME";
	String BS_DELTA_AUTOMATE_KEY = "AUTOMATE_KEY";
	String BS_DELTA_END_POINT = "END_POINT";

	// Browser Configuration - Serial 
	String BS_DELTA_BROWSER = "BROWSER";
	String BS_DELTA_BROWSER_VERSION = "BROWSER_VERSION";
	String BS_DELTA_OS = "OS";
	String BS_DELTA_OS_VERSION = "OS_VERSION";
	String  BS_DELTA_RESOLUTION = "RESOLUTION";
	String BS_DELTA_DEBUG = "DEBUG";
	String  BS_DELTA_BUILDSERIAL = "BUILDNAME_SERIAL";

	// Browser Names + Versions - for Parallel processing
	
	String BS_DELTA_OS_NAME = "OS_NAME";
	String BS_DELTA_OS_NAME_VERSION = "OS_NAME_VERSION";
	String BS_DELTA_BROWSER_NAME_1 = "BROWSER_NAME_1";
	String BS_DELTA_BROWSER_NAME_2 = "BROWSER_NAME_2";
	String BS_DELTA_BROWSER_NAME_3 = "BROWSER_NAME_3";
	String BS_DELTA_BROWSER_NAME_VERSION_1 = "BROWSER_NAME_VERSION_1";
	String BS_DELTA_BROWSER_NAME_VERSION_2 = "BROWSER_NAME_VERSION_2";
	String BS_DELTA_BROWSER_NAME_VERSION_3 = "BROWSER_NAME_VERSION_3"; 
	
	String BS_DELTA_BUILDPARALLEL = "BUILDNAME_PARALLEL";
	
	// Req 1
	String BS_DELTA_TEST_URL = "TEST_URL";
	String BS_DELTA_TEST_DIRECTION = "TEST_DIRECTION";
	String BS_DELTA_TEST_START_ELEMENT = "TEST_START_ELEMENT";
	String BS_DELTA_TEST_START = "TEST_START";
	String BS_DELTA_TEST_END_ELEMENT = "TEST_END_ELEMENT";
	String BS_DELTA_TEST_END = "TEST_END";
	String BS_DELTA_TEST_DATE_ELEMENT = "TEST_DATE_ELEMENT";
	String BS_DELTA_TEST_DATE = "TEST_DATE";

	// Req 2
	String BS_DELTA_TEST_URL2= "TEST_URL2";
	String BS_DELTA_FLIGHT_NUM_ELEMENT= "TEST_FLIGHT_NUM_ELEMENT";
	String BS_DELTA_FLIGHT_NUM ="TEST_FLIGHT_NUM";

	// Req 3
	String BS_DELTA_TEST_URL3 = "TEST_URL3";
	String BS_DELTA_HOTEL_SEARCH_CODE_ELE = "TEST_HOTEL_SEARCH_CODE_ELE";
	String BS_DELTA_HOTEL_SEARCH_CODE = "TEST_HOTEL_SEARCH";
	String BS_DELTA_CHECKIN_DATE_ELEM = "TEST_CHECKIN_DATE_ELEM";
	String BS_DELTA_CHECKIN_DATE = "TEST_CHECKIN_DATE";
	String BS_DELTA_CHECKOUT_DATE_ELEM = "TEST_CHECKOUT_DATE_ELEM";
	String BS_DELTA_CHECKOUT_DATE = "TEST_CHECKOUT_DATE";
}
